export const LOGIN = 'LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR'

export const LOGOUT = 'LOGOUT'

export const GET_CANDIDATES = 'GET_CANDIDATES'
export const GET_CANDIDATES_ERROR = 'GET_CANDIDATES_ERROR'

export const GET_CANDIDATE = 'GET_CANDIDATE'
export const GET_CANDIDATE_ERROR = 'GET_CANDIDATE_ERROR'

export const ADD_VOTE = 'ADD_VOTE'
export const ADD_VOTE_ERROR = 'ADD_VOTE_ERROR'

export const LOADING_USER = 'LOADING_USER'
export const LOADING_CANDIDATE = 'LOADING_CANDIDATE'
export const LOADING_VOTE = 'LOADING_VOTE'

export const REMOVE_ALERT = 'REMOVE_ALERT'
